sudo: false
language: ruby
rvm:
  - 2.4
before_install: gem install bundler -v 1.12.5
bundler_args: --without development
cache: bundler

addons:
  apt:
    packages:
      - diffutils

install:
  - bundle install --retry=3

script:

  # git complains if user and email are not set
  - git config --global user.name "Your Name"
  - git config --global user.email "you@example.com"

  - bundle exec rake
  - bundle exec rake install
