sudo: false
language: ruby
rvm:
  - 2.1.5
  - 2.2.5
before_install: gem install bundler -v 1.12.5
bundler_args: --without development
cache: bundler

addons:
  apt:
    packages:
      - diffutils

install:
  - bundle install --retry=3

script:
  - bundle exec rake
  - bundle exec rake build
